name: Spotless Check

on:
  push:
    branches:
      - '*'

jobs:
  spotless-apply:
    name: Spotless Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Run Spotless Apply
        run: mvn spotless:apply -DratchetFrom=main

  spotless-check:
    name: Spotless Check
    runs-on: ubuntu-latest
    needs: spotless-apply

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Run Spotless Check
        run: mvn spotless:check
        continue-on-error: true

      - name: Re-run Spotless Apply if Check Failed
        if: ${{ failure() }}
        run: mvn spotless:apply

  prevent-merge-if-failed:
    name: Prevent Merge if Spotless Check Failed
    runs-on: ubuntu-latest
    needs: spotless-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Check Spotless Status
        run: mvn spotless:check
        continue-on-error: true
        if: ${{ failure() }}

      - name: Prevent PRs and Force Pushes if Spotless Check Failed
        if: ${{ failure() }}
        run: |
          echo "::error::Spotless check failed. Changes cannot be merged."
          exit 1

  merge-and-finalize:
    name: Merge Changes and Finalize Spotless Apply
    runs-on: ubuntu-latest
    needs: prevent-merge-if-failed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Merge Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git merge ${{ github.ref }}

      - name: Run Spotless Apply on Entire Repository
        run: mvn spotless:apply
        continue-on-error: true

      - name: Re-run Spotless Apply if Failed
        if: ${{ failure() }}
        run: mvn spotless:apply
