on:
  push:
    branches:
      - main

jobs:
  spotless-check:
    name: Spotless Check
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK 22
        run: |
          wget -O jdk.tar.gz https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
          tar xvf jdk.tar.gz
          export JAVA_HOME=$PWD/jdk-16.0.2+7
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

      - name: Spotless Apply
        run: mvn spotless:apply

      - name: Check Spotless Status
        run: |
          git status
          git diff --exit-code

      - name: Fail on Spotless Check Failure
        if: failure()
        run: exit 1