name: Spotless Check

on:
  push:
    branches:
      - main

jobs:
  spotless-check:
    name: Spotless Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK 22
        run: |
          sudo add-apt-repository ppa:openjdk-r/ppa -y
          sudo apt-get update -q
          sudo apt-get install -y openjdk-22-jdk
          java -version

      - name: Spotless Apply
        run: mvn spotless:apply

      - name: Check Spotless Status
        run: |
          git status
          git diff --exit-code

      - name: Fail on Spotless Check Failure
        if: failure()
        run: exit 1